---
- hosts: backend
  gather_facts: yes

- hosts: frontend
  gather_facts: yes
  become: yes     
  roles:
    - role: common/users_mgmt
      vars:
        admin_group: 'adm'
        server_admin_list:
         - name: "Server Administrator"
           username: "serv-adm"
           keys:
             active:
               - "{{  adm_usr_pub }}"
#             disabled:
#               - "{{  adm_usr_pub_old }}"
           shell: "/bin/bash"   
           state: present
        users_group: 'users'
        users_server_list:           
         - name: "Server User"
           username: "serv-usr"
           keys:
             active:
               - "{{  srv_usr_pub }}"
#             disabled:
#               - "{{  srv_usr_pub_old }}"
           shell: "/bin/bash"   
           state: present   

    - role: common/nginx
      vars:
        webroot: "/srv/www/root"
        php_fpm_server: "{{ hostvars[groups['backend'][0]]['ansible_eth0']['ipv4']['address'] }}:9000"
        port: "8080"
        server_name: "morsh_nginx"

- hosts: backend
  become: yes     
  roles:
    - role: common/users_mgmt
      vars:
        admin_group: 'adm'
        server_admin_list:
         - name: "Server Administrator"
           username: "serv-adm"
           keys:
             active:
               - "{{  adm_usr_pub }}"
#             disabled:
#               - "{{  adm_usr_pub_old }}"
           shell: "/bin/bash"   
           state: present
        users_group: 'users'
        users_server_list:           
         - name: "Server User"
           username: "serv-usr"
           keys:
             active:
               - "{{  srv_usr_pub }}"
 #            disabled:
 #              - "{{  srv_usr_pub_old }}"
           shell: "/bin/bash"   
           state: present   

    - role: common/php
      vars:
       port: "9000"
       webroot: "/srv/www/root"
       nginx_ip: "{{ hostvars[groups['frontend'][0]]['ansible_eth0']['ipv4']['address'] }}"