---
- hosts: frontend
  gather_facts: yes
  become: yes     
  roles:
    - role: common/users_mgmt
      vars:
        admin_group: 'adm'
        server_admin_list:
         - name: "Server Administrator"
           username: "serv-adm"
           keys:
             active:
               - "{{  adm_ssh_pub }}"
             disabled:
               - "{{  user2_ssh_pub_old }}"
           shell: "/bin/bash"   
           state: present
        users_group: 'users'
        users_server_list:           
         - name: "Server User"
           username: "serv-usr"
           keys:
             active:
               - "{{  serv-usr_ssh_pub }}"
             disabled:
               - "{{  serv-usr_ssh_pub_old }}"
           shell: "/bin/bash"   
           state: present   

    - role: common/nginx
      vars:
        webroot: "/opt/nginx/ansible"
        port: "8080"
        server_name: "morsh_nginx"

- hosts: backend
  gather_facts: yes
  become: yes     
  roles:
    - role: common/users_mgmt
      vars:
        admin_group: 'adm'
        server_admin_list:
         - name: "Server Administrator"
           username: "serv-adm"
           keys:
             active:
               - "{{  adm_ssh_pub }}"
             disabled:
               - "{{  user2_ssh_pub_old }}"
           shell: "/bin/bash"   
           state: present
        users_group: 'users'
        users_server_list:           
         - name: "Server User"
           username: "serv-usr"
           keys:
             active:
               - "{{  serv-usr_ssh_pub }}"
             disabled:
               - "{{  serv-usr_ssh_pub_old }}"
           shell: "/bin/bash"   
           state: present   

    - role: common/php